export const arabicLexicon = {
  country: "البلد",
  userDashboard: "لوحة المستخدم",
  information: "معلومات:",
  changeAlert: "لقد تم التعديل على معلومات المستخدم يرجى حفظها قبل الخروج",
  firstName: "الاسم الأول",
  lastName: "اسم العائلة",
  dateOfBirth: "تاريخ الميلاد",
  underAgeError: "عمر المستخدم يجب أن يكون أكبر من 8 سنين",
  invalidDate: "تاريخ غير صحيح",
  companyName: "اسم الشركة",
  schoolName: "اسم المدرسة",
  countrySelectPlaceHolder: "اختر بلدك...",
  programmingLanguages: "لغات البرمجة",
  gender: "الجنس",
  genderSelectPlaceHolder: "اختر جنسك...",
  description: "وصف عنك",
  saveButtonText: "حفظ التغيرات",
  male: "ذكر",
  female: "أنثى",
  other: "أخر",
  programmingLanguagesPlaceHolder: "اختر اللغات...",
  selectAll: "اختر الجميع",
  unselectAll: "إزلة  الجميع",
  filterSelectAll: "جميع النتائج ",
  filterUnSelectAll: "إزالة جميع النتائج",
  searchPlaceholder: "ابحث",
  home: "الرئيسية",
  profile: "الشخصية",
  signIn: "دخول",
  signUp: "تسجيل",
  editProfile: "تعديل الصفحة الشخصية",
  signOut: "خروج",
  descriptionPlaceHolder: "اكتب عن نفسك...",
  weekdays: ["إث", "ث", "أر", "خ", "ج", "س", "أح"],
  months: [
    "يناير",
    "فبراير ",
    " مارس ",
    " أبريل ",
    " مايو",
    " يونيو",
    " يوليو ",
    "أغسطس",
    "سبتمبر ",
    " أكتوبر",
    "نوفمبر",
    " ديسمبر ",
  ],
  signedInSuccessFullyMessage: "أهلاً بك",
  signedOutMessage: "وداعًا",
  signedUpSucessFullyMessage: "تم التسجيل بنجاح",
  authGuardMessage: "تأكد أنت داخل بحسابك",
  preventUnsavedChangesGuardMessage:
    "لديك تعديلات لم يتم حفظها, هل أنت متأكد من الخروج؟ ",
  updatedSuccessfullyMessage: "تم التعديل بنجاح !",
  signedInFailedMessage: "هنالك خطأ باسم المستخدم أو كلمة السر",
  retrievingDataErrorMessage: "خطأ في استرجاع البيانات! ",
  signInFormSubtitle: "سجل دخولك لتكمل.",
  usernameOrEmail: "اسم المستخدم أو الإيميل",
  password: "كلمة السر",
  forgotPassword: "نسيت كلمة السر؟",
  newUser: "مستخدم جديد؟",
  createAccount: "أنشئ حسابك",
  usernameOrEmailRequiredErrorMessage: "اسم المستخدم أو الإيميل مطلوب",
  passwordRequiredErrorMessage: "كلمة السر مطلوبة",
  signUpFormSubtitle: "قم بالتسجيل لتكمل",
  email: "الإيميل",
  emailPatternErrorMessage: "إيميل خاظئ",
  emailRequiredErrorMessage: "الإيميل مطلوب",
  username: "اسم المستخدم",
  usernameLengthErrorMessage: "اسم المستخدم يجب أن يكون بين 8-20 حرف",
  usernamePatternErrorMessage: "اسم المستخدم ممنوع فيه ال@",
  passwordLengthErrorMessage: "كلمة السر يجب أن تكون بين 8-20 حرف",
  confirmPassword: "تأكيد كلمة السر",
  confirmPasswordMismatchErrorMessage: "لا يماثل كلمة السر",
  confirmPasswordRequiredErrorMessage: "تأكيد كلمة السر مطلوب",
  or: "أو",
  alreadyAUser: "لديك حساب؟",
  usernameRequiredErrorMessage: "اسم المستخدم مطلوب",
};
