import { AuthGuard } from "./../guards/auth.guard";
export const englishLexicon = {
  country: "Country",
  userDashboard: "User Dashboard",
  information: "Information:",
  changeAlert:
    "Changes were made to your profile, any unsaved changes will be gone !",
  firstName: "First Name",
  lastName: "Last Name",
  dateOfBirth: "Date of Birth",
  underAgeError: "User must be 8+ years old",
  invalidDate: "Invalid Date",
  companyName: "Company Name",
  schoolName: "School Name",
  countrySelectPlaceHolder: "Select your country...",
  programmingLanguages: "Programming Languages",
  gender: "Gender",
  genderSelectPlaceHolder: "Select your gender...",
  description: "Description",
  saveButtonText: "Save Changes",
  male: "Male",
  female: "Female",
  other: "Other",
  programmingLanguagesPlaceHolder: "Select your programming languages..",
  selectAll: "Select All",
  unselectAll: "Unselect All",
  filterSelectAll: "Select All Filtered",
  filterUnSelectAll: "Unselect All Filtered",
  searchPlaceholder: "Search",
  home: "Home",
  profile: "Profile",
  signIn: "Sign In",
  signUp: "Sign Up",
  editProfile: "Edit Profile",
  signOut: "Sign Out",
  descriptionPlaceHolder: "Write About Yourself...",
  weekdays: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
  months: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  signedInSuccessFullyMessage: "Welcome!",
  signedOutMessage: "Good bye!",
  signedUpSucessFullyMessage: "Registered Successfully!",
  authGuardMessage: "Make Sure You Are Signed in",
  preventUnsavedChangesGuardMessage:
    "Any unsaved changes won't be commited,are you sure you want to continue?",
  updatedSuccessfullyMessage: "Updated Successfully!",
  signedInFailedMessage: "Username or Password Incorrect!",
  retrievingDataErrorMessage: "Error in Retrieving Data!",
  signInFormSubtitle: "Sign in to continue.",
  usernameOrEmail: "Email or Username",
  password: "Password",
  forgotPassword: " Forgot Password ?",
  newUser: "New User?",
  createAccount: "Create an Account",
  usernameOrEmailRequiredErrorMessage: "Username or Email is Required",
  passwordRequiredErrorMessage: "Password is Required",
  signUpFormSubtitle: "Sign up to Continue",
  email: "Email",
  emailPatternErrorMessage: "Invalid Email",
  emailRequiredErrorMessage: "Email is Required",
  username: "Username",
  usernameRequiredErrorMessage: "Username is Required",
  usernameLengthErrorMessage: "Username Must Be Between 8-20 Characters",
  usernamePatternErrorMessage: "Username can't contain @",
  passwordLengthErrorMessage: "Password Must Be Between 8-20 Characters",
  confirmPassword: "Confirm Password",
  confirmPasswordMismatchErrorMessage: "Doesn't Match Password",
  confirmPasswordRequiredErrorMessage: "Confirm Password is Required",
  or: "or",
  alreadyAUser: "Already a User?",
};
