import { AuthGuard } from "../../guards/auth.guard";
const countries = {
  AF: "Afghanistan",
  AL: "Albania",
  AQ: "Antarctica",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AG: "Antigua and Barbuda",
  AZ: "Azerbaijan",
  AR: "Argentina",
  AU: "Australia",
  AT: "Austria",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  AM: "Armenia",
  BB: "Barbados",
  BE: "Belgium",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia (Plurinational State of)",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  BZ: "Belize",
  IO: "British Indian Ocean Territory",
  SB: "Solomon Islands",
  VG: "Virgin Islands (British)",
  BN: "Brunei Darussalam",
  BG: "Bulgaria",
  MM: "Myanmar",
  BI: "Burundi",
  BY: "Belarus",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cabo Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  LK: "Sri Lanka",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  TW: "Taiwan",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  YT: "Mayotte",
  CG: "Congo",
  CD: "Congo (Democratic Republic of the)",
  CK: "Cook Islands",
  CR: "Costa Rica",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  BJ: "Benin",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ET: "Ethiopia",
  ER: "Eritrea",
  EE: "Estonia",
  FO: "Faroe Islands",
  FK: "Falkland Islands (Malvinas)",
  GS: "South Georgia and the South Sandwich Islands",
  FJ: "Fiji",
  FI: "Finland",
  AX: "Åland Islands",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  DJ: "Djibouti",
  GA: "Gabon",
  GE: "Georgia",
  GM: "Gambia",
  PS: "Palestine, State of",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  KI: "Kiribati",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GN: "Guinea",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island and McDonald Islands",
  VA: "Holy See",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran (Islamic Republic of)",
  IQ: "Iraq",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  CI: "Côte d'Ivoire",
  JM: "Jamaica",
  JP: "Japan",
  KZ: "Kazakhstan",
  JO: "Jordan",
  KE: "Kenya",
  KP: "Korea (Democratic People's Republic of)",
  KR: "Korea (Republic of)",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Lao People's Democratic Republic",
  LB: "Lebanon",
  LS: "Lesotho",
  LV: "Latvia",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  MX: "Mexico",
  MC: "Monaco",
  MN: "Mongolia",
  MD: "Moldova (Republic of)",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  OM: "Oman",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  CW: "Curaçao",
  AW: "Aruba",
  SX: "Sint Maarten (Dutch part)",
  BQ: "Bonaire, Sint Eustatius and Saba",
  NC: "New Caledonia",
  VU: "Vanuatu",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  NO: "Norway",
  MP: "Northern Mariana Islands",
  UM: "United States Minor Outlying Islands",
  FM: "Micronesia (Federated States of)",
  MH: "Marshall Islands",
  PW: "Palau",
  PK: "Pakistan",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  GW: "Guinea-Bissau",
  TL: "Timor-Leste",
  PR: "Puerto Rico",
  QA: "Qatar",
  XK: "Republic of Kosovo",
  RE: "Réunion",
  RO: "Romania",
  RU: "Russian Federation",
  RW: "Rwanda",
  BL: "Saint Barthélemy",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  KN: "Saint Kitts and Nevis",
  AI: "Anguilla",
  LC: "Saint Lucia",
  MF: "Saint Martin (French part)",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent and the Grenadines",
  SM: "San Marino",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  VN: "Viet Nam",
  SI: "Slovenia",
  SO: "Somalia",
  ZA: "South Africa",
  ZW: "Zimbabwe",
  ES: "Spain",
  SS: "South Sudan",
  SD: "Sudan",
  EH: "Western Sahara",
  SR: "SuriName",
  SJ: "Svalbard and Jan Mayen",
  SZ: "Swaziland",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syrian Arab Republic",
  TJ: "Tajikistan",
  TH: "Thailand",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  AE: "United Arab Emirates",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks and Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  MK: "Macedonia (the former Yugoslav Republic of)",
  EG: "Egypt",
  GB: "United Kingdom of Great Britain and Northern Ireland",
  GG: "Guernsey",
  JE: "Jersey",
  IM: "Isle of Man",
  TZ: "Tanzania, United Republic of",
  US: "United States of America",
  VI: "Virgin Islands (U.S.)",
  BF: "Burkina Faso",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VE: "Venezuela (Bolivarian Republic of)",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  YE: "Yemen",
  ZM: "Zambia",
};
export const englishLexicon = {
  country: "Country",
  userDashboard: "User Dashboard",
  information: "Information:",
  changeAlert:
    "Changes were made to your profile, any unsaved changes will be gone !",
  firstName: "First Name",
  lastName: "Last Name",
  dateOfBirth: "Date of Birth",
  underAgeError: "User must be 8+ years old",
  invalidDate: "Invalid Date",
  companyName: "Company Name",
  schoolName: "School Name",
  countrySelectPlaceHolder: "Select your country...",
  programmingLanguages: "Programming Languages",
  gender: "Gender",
  genderSelectPlaceHolder: "Select your gender...",
  description: "Description",
  saveButtonText: "Save Changes",
  male: "Male",
  female: "Female",
  other: "Other",
  programmingLanguagesPlaceHolder: "Select your programming languages..",
  selectAll: "Select All",
  unselectAll: "Unselect All",
  filterSelectAll: "Select All Filtered",
  filterUnSelectAll: "Unselect All Filtered",
  searchPlaceholder: "Search",
  home: "Home",
  profile: "Profile",
  signIn: "Sign In",
  signUp: "Sign Up",
  editProfile: "Edit Profile",
  signOut: "Sign Out",
  descriptionPlaceHolder: "Write About Yourself...",
  weekdays: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
  months: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  signedInSuccessFullyMessage: "Welcome!",
  signedOutMessage: "Good bye!",
  signedUpSucessFullyMessage: "Registered Successfully!",
  authGuardMessage: "Make Sure You Are Signed in",
  preventUnsavedChangesGuardMessage:
    "Any unsaved changes won't be commited,are you sure you want to continue?",
  updatedSuccessfullyMessage: "Updated Successfully!",
  signedInFailedMessage: "Username or Password Incorrect!",
  retrievingDataErrorMessage: "Error in Retrieving Data!",
  signInFormSubtitle: "Sign in to continue.",
  usernameOrEmail: "Email or Username",
  password: "Password",
  forgotPassword: " Forgot Password ?",
  newUser: "New User?",
  createAccount: "Create an Account",
  usernameOrEmailRequiredErrorMessage: "Username or Email is Required",
  passwordRequiredErrorMessage: "Password is Required",
  signUpFormSubtitle: "Sign up to Continue",
  email: "Email",
  emailPatternErrorMessage: "Invalid Email",
  emailRequiredErrorMessage: "Email is Required",
  username: "Username",
  usernameRequiredErrorMessage: "Username is Required",
  usernameLengthErrorMessage: "Username Must Be Between 8-20 Characters",
  usernamePatternErrorMessage: "Username can't contain @",
  passwordLengthErrorMessage: "Password Must Be Between 8-20 Characters",
  confirmPassword: "Confirm Password",
  confirmPasswordMismatchErrorMessage: "Doesn't Match Password",
  confirmPasswordRequiredErrorMessage: "Confirm Password is Required",
  or: "or",
  alreadyAUser: "Already a User?",
  changePhoto: "Change Your Photo",
  uploadPhoto: "Upload Photo",
  ...countries,
  projectName: "Grad-Proj",
  projectLocation: "Amman-Jordan",
  projectPhoneNumber: "077xxxxxx",
  projectEmail: "Gradproj@company.com",
  about: "About",
  why: "Why",
  mission: "Mission and Goals",
  regulation: "Regulation ",
  questionMark: "?",
  posts: "Posts",
  create: "Create",
  new: "New",
  cancel: "Cancel",
  title: "Title",
  titleLengthErrorMessage: "Title Must Be Between 20-400 characters",
  titleIsRequiredErrorMessage: "Title Is Required",
  emailUsedErrorMessage: "Email Is Used",
  usernameUsedErrorMessage: "Username Is Used",
  back: "Back",
  createdAt: "Created at:",
  leaveAComment: "Leave a comment:",
  edit: "Edit",
  save: "Save",
  report: "Report",
  signInToCommentMessage: "Sign in to Comment...",
  postSuccessfullySubmittedMessage: "Post Successfully Created!",
  commentSuccessfullySubmittedMessege: "Comment Successfully Created!",
  postFailedSubmittionMessage: "Post Failed to be Created",
  commentFailedSubmittionMessage: "Comment Failed to be Created",
  share: "Share",
  dateEdited: "Date of the Last Edit",
  dateAdded: "Date of Creation",
  homeFirstParagraphTitle: "A New Place to Find Solutions For Your Bugs",
  homeFirstParagraphBody:
    "Grad-Proj is a new platform to help you enhance your skills, expand your knowledge and fix your bugs.",
  createAccountLinkText: "Create Account Now",
  homeSecondParagphTitle: "Start Exploring",
  homeSecondParagphBody: `Grad-Proj is a project that focuses on helping out both the Arab and
   non-Arab developers of the world, explore its posts in which you canhelp others or create your
    own post and ask for other developers' help.`,
  getStartedLinkText: "Get Started",
};
